#ifndef POTENTIOMETER_CFG_H_
#define POTENTIOMETER_CFG_H_

/**
	Potentiometer ADC Channel Options
		ADC_CHANNEL_0
		ADC_CHANNEL_1
		ADC_CHANNEL_2
		ADC_CHANNEL_3
		ADC_CHANNEL_4
		ADC_CHANNEL_5
		ADC_CHANNEL_6
		ADC_CHANNEL_7
*/

#define POTENTIOMETER_ADC_CHANNEL ADC_CHANNEL_1

#endif