#ifndef LDR_CFG_H_
#define LDR_CFG_H_

/**
	LDR ADC Channel Options
		ADC_CHANNEL_0
		ADC_CHANNEL_1
		ADC_CHANNEL_2
		ADC_CHANNEL_3
		ADC_CHANNEL_4
		ADC_CHANNEL_5
		ADC_CHANNEL_6
		ADC_CHANNEL_7
*/

#define LDR_ADC_CHANNEL ADC_CHANNEL_0

#endif