#include "../../MCAL/DIO/DIO_CFG.h"
#include "../../MCAL/DIO/DIO_Interface.h"
#include "STPM_Private.h"
#include "STPM_CFG.h"
#include "STPM_Interface.h"

void STPM_voidInitMotor(void)
{
	DIO_voidSetPinDirection(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_OUTPUT);
	DIO_voidSetPinDirection(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_OUTPUT);
	DIO_voidSetPinDirection(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_OUTPUT);
	DIO_voidSetPinDirection(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_OUTPUT);
}
void STPM_voidRotateCW(void)
{
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_HIGH);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_LOW);
	_delay_ms(100);
	
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_HIGH);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_LOW);
	_delay_ms(100);
	
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_HIGH);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_LOW);
	_delay_ms(100);
	
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_HIGH);
	_delay_ms(100);
}
void STPM_voidRotateACW(void)
{
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_HIGH);
	_delay_ms(100);
	
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_HIGH);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_LOW);
	_delay_ms(100);
	
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_HIGH);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_LOW);
	_delay_ms(100);
	
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_BLUE_PIN, DIO_PIN_HIGH);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_PINK_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_YELLOW_PIN, DIO_PIN_LOW);
	DIO_voidSetPinValue(STPM_PORT, STPM_COIL_ORANGE_PIN, DIO_PIN_LOW);
	_delay_ms(100);
}